import { renderCard } from '../../components/ProductCard.js';
import '../../styles/catalog.css';

export function filterProducts(products, filters) { const query = filters.query.trim().toLowerCase(); return products.filter((product) => { const haystack = [product.title, product.description, product.category].filter(Boolean).join(' ').toLowerCase(); return (!query || haystack.includes(query)) && (filters.category === 'all' || product.category === filters.category) && (!filters.minPrice || product.price >= filters.minPrice) && (!filters.maxPrice || product.price <= filters.maxPrice); }); }
export function sortProducts(products, sort) { const reviewsOf = (product) => Array.isArray(product.reviews) ? product.reviews.length : product.reviews || 0; return [...products].sort((a, b) => { if (sort === 'price-asc') return a.price - b.price; if (sort === 'price-desc') return b.price - a.price; if (sort === 'rating') return Number(b.rating) - Number(a.rating); if (sort === 'new') return Number(Boolean(b.isNew)) - Number(Boolean(a.isNew)) || b.id - a.id; if (sort === 'name') return a.title.localeCompare(b.title, 'ru'); return reviewsOf(b) - reviewsOf(a) || Number(b.rating) - Number(a.rating); }); }
export function renderFilters(categories) { return `<aside class="catalog-filters"><div class="filter-heading"><b>Категории</b><button type="button" data-catalog-reset>Сбросить</button></div><div class="catalog-categories"><button type="button" class="catalog-category is-active" data-catalog-category="all">Все</button>${categories.map((category) => `<button type="button" class="catalog-category" data-catalog-category="${category}">${category}</button>`).join('')}</div><div class="catalog-price"><b>Цена, сум</b><div><input data-catalog-min type="number" min="0" placeholder="От"><input data-catalog-max type="number" min="0" placeholder="До"></div></div></aside>`; }
function renderProductGrid(products, favorites, formatPrice, cart) { return products.map((product, index) => `<div class="catalog-product" data-product-index="${index}">${renderCard(product, favorites, formatPrice, cart)}</div>`).join(''); }
function mountCatalog(products, options = {}) {
  const root = document.querySelector('[data-catalog-root]'); if (!root || root.dataset.mounted) return; root.dataset.mounted = 'true';
  const state = { query: options.initialQuery || '', category: options.initialCategory || 'all', sort: 'popular', minPrice: 0, maxPrice: 0 }; const search = root.querySelector('[data-catalog-search]'); const sort = root.querySelector('[data-catalog-sort]'); const min = root.querySelector('[data-catalog-min]'); const max = root.querySelector('[data-catalog-max]'); const counter = root.querySelector('[data-catalog-count]'); const grid = root.querySelector('[data-catalog-grid]'); const categoryButtons = [...root.querySelectorAll('[data-catalog-category]')]; const cards = [...root.querySelectorAll('.catalog-product')];
  search.value = state.query;
  categoryButtons.forEach((button) => button.classList.toggle('is-active', button.dataset.catalogCategory === state.category));
  const update = () => { const visible = sortProducts(filterProducts(products, state), state.sort); const indexes = new Set(visible.map((product) => products.indexOf(product))); cards.forEach((card, index) => { card.hidden = !indexes.has(index); }); visible.forEach((product) => grid.append(cards[products.indexOf(product)])); counter.textContent = `Найдено товаров: ${visible.length}`; const empty = root.querySelector('[data-catalog-empty]'); if (!visible.length && !empty) grid.insertAdjacentHTML('afterend', '<div class="catalog-empty" data-catalog-empty><span>🔍</span><h2>Ничего не найдено</h2><p>Попробуйте изменить поиск</p></div>'); if (visible.length && empty) empty.remove(); };
  search.addEventListener('input', () => { state.query = search.value; update(); }); sort.addEventListener('change', () => { state.sort = sort.value; update(); }); [min, max].forEach((input) => input.addEventListener('input', () => { state.minPrice = Number(min.value) || 0; state.maxPrice = Number(max.value) || 0; update(); })); categoryButtons.forEach((button) => button.addEventListener('click', () => { state.category = button.dataset.catalogCategory; categoryButtons.forEach((item) => item.classList.toggle('is-active', item === button)); update(); })); root.querySelector('[data-catalog-reset]').addEventListener('click', () => { Object.assign(state, { query: '', category: 'all', sort: 'popular', minPrice: 0, maxPrice: 0 }); search.value = ''; sort.value = 'popular'; min.value = ''; max.value = ''; categoryButtons.forEach((item) => item.classList.toggle('is-active', item.dataset.catalogCategory === 'all')); update(); });
}
export function renderCatalogPage({ products = [], favorites = [], formatPrice, cart = [], categories = [], initialQuery = '', initialCategory = 'all' }) { const categoryList = categories.length ? categories : [...new Set(products.map((product) => product.category).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'ru')); setTimeout(() => mountCatalog(products, { initialQuery, initialCategory }), 0); return `<main class="wrap catalog-page" data-catalog-root><div class="crumb">Главная / Каталог</div><h1>Каталог товаров</h1><div class="catalog-toolbar"><label class="catalog-search"><span>⌕</span><input type="search" data-catalog-search placeholder="Поиск по названию товара" autocomplete="off"></label><label class="catalog-sort">Сортировка<select data-catalog-sort><option value="popular">По популярности</option><option value="price-asc">Сначала дешевле</option><option value="price-desc">Сначала дороже</option><option value="rating">По рейтингу</option><option value="name">По названию</option></select></label></div><div class="catalog-layout">${renderFilters(categoryList)}<section class="catalog-results"><p class="catalog-count" data-catalog-count>Найдено товаров: ${products.length}</p><div class="grid catalog-grid" data-catalog-grid>${renderProductGrid(products, favorites, formatPrice, cart)}</div></section></div></main>`; }
